const { MongoClient } = require("mongodb");

async function run() {
  const client = new MongoClient(
    "mongodb+srv://shivanshunigam8:ZU%3FgxpA%26TgbG4VY@shiva-db.axovoox.mongodb.net/db1?retryWrites=true&w=majority&appName=shiva-db"
  );
  await client.connect();
  const db = client.db("db1");
  const collection = db.collection("competitionproducts");

  await collection.insertMany([
    {
      brand: "Eicher",
      model: "Pro 2049",
      category: "SCV Cargo",
      description:
        "The Eicher Pro 2049 is a high-performing light-duty truck with superior fuel efficiency and class-leading payload, ideal for intra-city cargo movement.",
      mileage: "14 km/l",
      price: "950000",
      engine: "E366 2.0L CRS Diesel 100 HP",
      fuelType: "Diesel",
      fuelTankCapacity: "38",
      gearBox: "5-Speed Manual",
      clutchDia: "280 mm",
      torque: "285 Nm @ 1200-1600 rpm",
      tyre: "7.00R16 Radial",
      cabinType: "Day Cabin",
      warranty: "3 Years / Unlimited Km",
      applicationSuitability:
        "City logistics, E-commerce, FMCG, Market Load, Parcel & Courier",
      payload: "2000 Kg",
      bodyDimensions: "3200*1900*400 mm",
      monitoringFeatures: ["Eicher Live telematics", "Driver Scorecard"],
      driverComfort: 8,
      images: [
        "https://res.cloudinary.com/dsadzuh5q/image/upload/v1760165000/competition/eicher_pro2049.png",
      ],
      brochureFile: {
        filename: "1760165001-eicher-pro2049.pdf",
        path: "/root/vikramshila-BE/uploads/brochures/1760165001-eicher-pro2049.pdf",
        mimetype: "application/pdf",
      },
      newLaunch: 0,
      createdAt: new Date(),
    },
    {
      brand: "Ashok Leyland",
      model: "Bada Dost i4",
      category: "SCV Pickup",
      description:
        "Ashok Leyland Bada Dost i4 offers best-in-class payload, strong performance, and high driver comfort for long duty cycles.",
      mileage: "13 km/l",
      price: "980000",
      engine: "1.5L TDCR Diesel 80 HP",
      fuelType: "Diesel",
      fuelTankCapacity: "40",
      gearBox: "5-Speed Synchromesh",
      clutchDia: "240 mm",
      torque: "190 Nm @ 1600-2400 rpm",
      tyre: "195 R15 LT Radial",
      cabinType: "Single Cabin",
      warranty: "3 Years / 150000 Km",
      applicationSuitability:
        "Market Load, Agriculture, Dairy, FMCG, Construction Material",
      payload: "2000 Kg",
      bodyDimensions: "2980*1750*400 mm",
      monitoringFeatures: ["Telematics ready", "Fleet Management system"],
      driverComfort: 9,
      images: [
        "https://res.cloudinary.com/dsadzuh5q/image/upload/v1760165050/competition/ashok_leyland_bada_dost.png",
      ],
      brochureFile: {
        filename: "1760165051-bada-dost.pdf",
        path: "/root/vikramshila-BE/uploads/brochures/1760165051-bada-dost.pdf",
        mimetype: "application/pdf",
      },
      newLaunch: 0,
      createdAt: new Date(),
    },
    {
      brand: "Mahindra",
      model: "Jeeto Plus CNG 400",
      category: "SCV Cargo",
      description:
        "Mahindra Jeeto Plus CNG 400 offers unmatched mileage and performance for last-mile cargo delivery in cities.",
      mileage: "30 km/kg",
      price: "520000",
      engine: "625cc Water Cooled CNG Engine 16 HP",
      fuelType: "CNG",
      fuelTankCapacity: "40",
      gearBox: "4-Speed Manual",
      clutchDia: "190 mm",
      torque: "38 Nm @ 1200-2000 rpm",
      tyre: "145 R12",
      cabinType: "Single Cabin",
      warranty: "2 Years / 40000 Km",
      applicationSuitability:
        "City deliveries, FMCG, Parcel & Courier, Market Load",
      payload: "1000 Kg",
      bodyDimensions: "2000*1400*300 mm",
      monitoringFeatures: ["Basic telematics optional"],
      driverComfort: 7,
      images: [
        "https://res.cloudinary.com/dsadzuh5q/image/upload/v1760165090/competition/mahindra_jeeto_cng.png",
      ],
      brochureFile: {
        filename: "1760165091-mahindra-jeeto.pdf",
        path: "/root/vikramshila-BE/uploads/brochures/1760165091-mahindra-jeeto.pdf",
        mimetype: "application/pdf",
      },
      newLaunch: 0,
      createdAt: new Date(),
    },
    {
      brand: "Piaggio",
      model: "Ape Xtra LDX Diesel",
      category: "SCV Cargo",
      description:
        "Piaggio Ape Xtra LDX is a proven performer for urban and semi-urban cargo, delivering high fuel economy and robust reliability.",
      mileage: "28 km/l",
      price: "450000",
      engine: "597cc Diesel, Single Cylinder, 9.5 HP",
      fuelType: "Diesel",
      fuelTankCapacity: "10.5",
      gearBox: "5-Speed Manual",
      clutchDia: "170 mm",
      torque: "23.5 Nm @ 2000 rpm",
      tyre: "4.5 x 10",
      cabinType: "Single Cabin",
      warranty: "18 months / 1 Year",
      applicationSuitability:
        "Urban deliveries, groceries, logistics, construction",
      payload: "750 Kg",
      bodyDimensions: "2200*1400*350 mm",
      monitoringFeatures: ["Fleet tracking optional"],
      driverComfort: 6,
      images: [
        "https://res.cloudinary.com/dsadzuh5q/image/upload/v1760165200/competition/piaggio_ape_ldx.png",
      ],
      brochureFile: {
        filename: "1760165201-piaggio-ape.pdf",
        path: "/root/vikramshila-BE/uploads/brochures/1760165201-piaggio-ape.pdf",
        mimetype: "application/pdf",
      },
      newLaunch: 0,
      createdAt: new Date(),
    },
    {
      brand: "Force",
      model: "Kargo King",
      category: "SCV Cargo",
      description:
        "Force Kargo King is a versatile cargo vehicle with a strong chassis and excellent torque for hilly and rough terrain performance.",
      mileage: "14 km/l",
      price: "870000",
      engine: "FM2.6CR Common Rail Diesel 80 HP",
      fuelType: "Diesel",
      fuelTankCapacity: "45",
      gearBox: "5-Speed Manual",
      clutchDia: "260 mm",
      torque: "230 Nm @ 1400 rpm",
      tyre: "185 R14 Radial",
      cabinType: "Single Cabin",
      warranty: "3 Years / 150000 Km",
      applicationSuitability:
        "Rural logistics, construction material, e-commerce, FMCG",
      payload: "1500 Kg",
      bodyDimensions: "2800*1600*400 mm",
      monitoringFeatures: ["GPS tracking optional"],
      driverComfort: 8,
      images: [
        "https://res.cloudinary.com/dsadzuh5q/image/upload/v1760165230/competition/force_kargo_king.png",
      ],
      brochureFile: {
        filename: "1760165231-force-kargo.pdf",
        path: "/root/vikramshila-BE/uploads/brochures/1760165231-force-kargo.pdf",
        mimetype: "application/pdf",
      },
      newLaunch: 0,
      createdAt: new Date(),
    },
    {
      brand: "Isuzu",
      model: "D-Max S-CAB",
      category: "Pickup",
      description:
        "The Isuzu D-Max S-CAB is a powerful and reliable pickup built for commercial logistics, offering unmatched durability and comfort.",
      mileage: "12 km/l",
      price: "1400000",
      engine: "2.5L VGS Turbo Diesel 78 HP",
      fuelType: "Diesel",
      fuelTankCapacity: "55",
      gearBox: "5-Speed Manual",
      clutchDia: "275 mm",
      torque: "176 Nm @ 1500 rpm",
      tyre: "215/70 R15",
      cabinType: "Dual Cabin",
      warranty: "3 Years / 100000 Km",
      applicationSuitability: "FMCG, Pharma, Courier, Rural Logistics",
      payload: "1200 Kg",
      bodyDimensions: "2700*1800*400 mm",
      monitoringFeatures: ["Telematics ready"],
      driverComfort: 9,
      images: [
        "https://res.cloudinary.com/dsadzuh5q/image/upload/v1760165270/competition/isuzu_dmax.png",
      ],
      brochureFile: {
        filename: "1760165271-isuzu-dmax.pdf",
        path: "/root/vikramshila-BE/uploads/brochures/1760165271-isuzu-dmax.pdf",
        mimetype: "application/pdf",
      },
      newLaunch: 0,
      createdAt: new Date(),
    },
    {
      brand: "Mahindra",
      model: "Bolero Maxx HD 1.7 VXi",
      category: "Pickup",
      description:
        "Mahindra Bolero Maxx HD 1.7 VXi offers heavy-duty performance with superior payload, reliability, and fuel efficiency.",
      mileage: "15 km/l",
      price: "1100000",
      engine: "m2Di 2523cc Diesel 80 HP",
      fuelType: "Diesel",
      fuelTankCapacity: "45",
      gearBox: "5-Speed Manual",
      clutchDia: "260 mm",
      torque: "220 Nm @ 1500 rpm",
      tyre: "195 R15 LT",
      cabinType: "Single Cabin",
      warranty: "3 Years / 100000 Km",
      applicationSuitability: "Construction, FMCG, E-commerce, Market Load",
      payload: "1700 Kg",
      bodyDimensions: "3000*1750*400 mm",
      monitoringFeatures: ["Telematics ready", "GPS tracking"],
      driverComfort: 8,
      images: [
        "https://res.cloudinary.com/dsadzuh5q/image/upload/v1760165300/competition/mahindra_bolero_maxx.png",
      ],
      brochureFile: {
        filename: "1760165301-bolero-maxx.pdf",
        path: "/root/vikramshila-BE/uploads/brochures/1760165301-bolero-maxx.pdf",
        mimetype: "application/pdf",
      },
      newLaunch: 0,
      createdAt: new Date(),
    },
    {
      brand: "Ashok Leyland",
      model: "Partner 4T",
      category: "LCV",
      description:
        "Ashok Leyland Partner 4T delivers high power with superior payload and driver comfort, suited for medium-distance cargo.",
      mileage: "11 km/l",
      price: "1650000",
      engine: "ZD30 Diesel 118 HP",
      fuelType: "Diesel",
      fuelTankCapacity: "90",
      gearBox: "5-Speed Manual",
      clutchDia: "310 mm",
      torque: "320 Nm @ 2400 rpm",
      tyre: "7.50 R16",
      cabinType: "Day Cabin",
      warranty: "3 Years / 200000 Km",
      applicationSuitability:
        "E-commerce, Cement, Market Load, Hardware Supply",
      payload: "4000 Kg",
      bodyDimensions: "4800*2100*700 mm",
      monitoringFeatures: ["Telematics system"],
      driverComfort: 8,
      images: [
        "https://res.cloudinary.com/dsadzuh5q/image/upload/v1760165330/competition/ashok_partner.png",
      ],
      brochureFile: {
        filename: "1760165331-ashok-partner.pdf",
        path: "/root/vikramshila-BE/uploads/brochures/1760165331-ashok-partner.pdf",
        mimetype: "application/pdf",
      },
      newLaunch: 0,
      createdAt: new Date(),
    },
    {
      brand: "BharatBenz",
      model: "1015R Plus",
      category: "LCV",
      description:
        "BharatBenz 1015R Plus provides high reliability and superior mileage for medium-duty applications.",
      mileage: "9 km/l",
      price: "1650000",
      engine: "4D34i 3907cc Diesel 147 HP",
      fuelType: "Diesel",
      fuelTankCapacity: "171",
      gearBox: "6-Speed Manual",
      clutchDia: "362 mm",
      torque: "460 Nm @ 1500 rpm",
      tyre: "8.25 R20 Radial",
      cabinType: "Day Cabin",
      warranty: "4 Years / Unlimited Km",
      applicationSuitability:
        "Construction Material, E-Commerce, Container Applications",
      payload: "7000 Kg",
      bodyDimensions: "5500*2200*700 mm",
      monitoringFeatures: ["Daimler FleetConnect", "GPS tracking"],
      driverComfort: 9,
      images: [
        "https://res.cloudinary.com/dsadzuh5q/image/upload/v1760165120/competition/bharatbenz_1015r.png",
      ],
      brochureFile: {
        filename: "1760165121-bharatbenz-1015r.pdf",
        path: "/root/vikramshila-BE/uploads/brochures/1760165121-bharatbenz-1015r.pdf",
        mimetype: "application/pdf",
      },
      newLaunch: 0,
      createdAt: new Date(),
    },
    {
      brand: "Eicher",
      model: "Pro 3015",
      category: "ICV",
      description:
        "Eicher Pro 3015 offers exceptional load capacity and mileage with advanced EUTECH6 technology for intercity haulage.",
      mileage: "8.5 km/l",
      price: "1800000",
      engine: "E494 3760cc Diesel 160 HP",
      fuelType: "Diesel",
      fuelTankCapacity: "190",
      gearBox: "6-Speed Manual",
      clutchDia: "352 mm",
      torque: "500 Nm @ 1200 rpm",
      tyre: "8.25R20 Radial",
      cabinType: "Day Cabin",
      warranty: "4 Years / 300000 Km",
      applicationSuitability: "Steel, Cement, White Goods, FMCG, Logistics",
      payload: "8000 Kg",
      bodyDimensions: "5800*2200*700 mm",
      monitoringFeatures: ["Eicher Live", "Fuel Coaching", "Trip Report"],
      driverComfort: 8,
      images: [
        "https://res.cloudinary.com/dsadzuh5q/image/upload/v1760165400/competition/eicher_pro3015.png",
      ],
      brochureFile: {
        filename: "1760165401-eicher-pro3015.pdf",
        path: "/root/vikramshila-BE/uploads/brochures/1760165401-eicher-pro3015.pdf",
        mimetype: "application/pdf",
      },
      newLaunch: 0,
      createdAt: new Date(),
    },
  ]);

  console.log("Inserted successfully!");
  await client.close();
}

run().catch(console.error);
